### ISSUE TITLE
Add to DockerHub

### ISSUE THREAD

**Issue by emilorol** [karol-brejna-i/docker-locust#11]
Can you add the new version to DockerHub?

PR #9 (merged)

**Comment by karol-brejna-i** [comment]
@emilorol Looks like 0.13.5 is not able to start a slave. (See notest to #10)
Your updated example proved that there is a problem there.
I remember using 0.13.0 in docker and it was all ok. Maybe a Locust bug?

**Comment by emilorol** [comment]
Locust deprecated something that affected the locustfile.py, but there was a collision with an ENV variable.

I have updated the code in PR #10

**Comment by emilorol** [comment]
Any luck testing?

**Comment by karol-brejna-i** [comment]
Yes. The only other thing that kept me from merging was lack of documentation for the changed env variable (LOCUST_MASTER_HOST) and that the example doesn't work for the previous versions...

I decided it can be fixed later.

Thanks for the contribution.

**Comment by karol-brejna-i** [comment]
https://hub.docker.com/layers/grubykarol/locust/0.13.5-python3.8-alpine3.11/images/sha256-424a3d06a1fcfbddebb287d247f73d53d9f45c6c2151a2505ef0eb9aff3c2ad5
