### ISSUE TITLE
Support Locust v1.0.x

### ISSUE THREAD

**Issue by youngkih** [karol-brejna-i/docker-locust#15]
Locust seems to have released new version with v1.0.x . It would be great to have this supported here. Example would be like
```
FROM python:3.8.1-alpine3.11

COPY docker-entrypoint.sh /

RUN    apk --no-cache add --virtual=.build-dep build-base git \
    && apk --no-cache add zeromq-dev libffi-dev \
    && python3 -m pip install --no-cache-dir git+https://github.com/locustio/locust.git@1.0.2#egg=locustio  \
    && apk del .build-dep \
    && chmod +x /docker-entrypoint.sh \
    && mkdir /locust
WORKDIR /locust
EXPOSE 8089 5557 5558

ENTRYPOINT ["/docker-entrypoint.sh"]
```

**Comment by karol-brejna-i** [comment]
@youngkih Sorry, for the late answer. Would you consider creating a PR?

**Comment by youngkih** [comment]
> @youngkih Sorry, for the late answer. Would you consider creating a PR?

Hi @karol-brejna-i , sure, but seems like i don't have the access to push my change
```
locust-1.0.3 ✔ $ git push origin locust-1.0.3
ERROR: Permission to karol-brejna-i/docker-locust.git denied to youngkih.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
Could you grant access to create PR for this change?

**Comment by karol-brejna-i** [comment]
@youngkih the usual workflow would look like this:
1. You fork the repo
2. You make a dedicated branch (on the forked repo)
3. You make desired changes 
4. You commit the changes (after validating if the image works, adding it to examples, etc.)
4. You create a pull request

Then I would be able to accept and merge the PR.

Please, go ahead and try. It's a bit of work, but on the other hand -- it would be your Open Source contribution!

**Comment by youngkih** [comment]
> @youngkih the usual workflow would look like this:
> 
> 1. You fork the repo
> 2. You make a dedicated branch (on the forked repo)
> 3. You make desired changes
> 4. You commit the changes (after validating if the image works, adding it to examples, etc.)
> 5. You create a pull request
> 
> Then I would be able to accept and merge the PR.
> 
> Please, go ahead and try. It's a bit of work, but on the other hand -- it would be your Open Source contribution!

@karol-brejna-i Thanks for the detailed instruction! Would love to try it out, will let you know when i open a PR 🙏

**Comment by youngkih** [comment]
@karol-brejna-i I've opened https://github.com/karol-brejna-i/docker-locust/pull/16, please help take a look. I'll close this issue, let's keep track of this update with the PR
