### ISSUE TITLE
Update README with new locust mode 'worker' instead of 'slave'

### ISSUE THREAD

**Issue by eeerikjansen** [karol-brejna-i/docker-locust#17]
Currently the README notes the following:

> LOCUST_MODE | Set the mode to run in. Can be standalone, master or slave.

In the latest locust versions this is changed to 'worker' instead of 'slave'

**Comment by karol-brejna-i** [comment]
Thanks for spotting this.

**Comment by karol-brejna-i** [comment]
Resolved with external PR

**Comment by karol-brejna-i** [comment]
Resolved with external PR
