### ISSUE TITLE
make docker images public available through docker hub

### ISSUE THREAD

**Issue by lkwg82** [karol-brejna-i/docker-locust#7]
Hi *,

I really like the work you did and are willing to help to make them easily usable  within `FROM ...`in docker.

What do you think about?

**Comment by karol-brejna-i** [comment]
@lkwg82 I am open to contributions :) 
Could you propose/describe your changes here? 
Also, you could just fork and introduce the required changes straight away.

**Comment by lkwg82** [comment]
I thought about connecting your repository with docker-hub and then we are done.

I dont want to fork it. Then we have decentralised it and I have the burden of maintenance.

**Comment by karol-brejna-i** [comment]
Forking was ment to be a first step for making a Pull Request (if source code needs to be modified).
After merging the PR, the fork could be removed.

The images are published in the docker hub already:
* for version 0.11.x, 0.12.x
* after every merge to master

See: https://cloud.docker.com/u/grubykarol/repository/docker/grubykarol/locust

Again, I am open to any suggestions/corrections/...

**Comment by lkwg82** [comment]
you already publish? Then I just add a link and then we are fine.
